### ISSUE TITLE
2021-05-17 Staff Meeting

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#103]
# 2021-05-17 SeaGL 2021 bi-weekly all-hands
- May 17th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/staff/issues/32)
- [Shared Pad](https://etherpad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 

### Metrics (previous --> current)
- N/A (start brainstorming)

### Previous meeting feedback
- many kudos
  - deb: yay new faces, yay committees, yay momentum
  - rhiannon: nothing to add
  - salt: yay all of the faces
  - alison: puppy! pre-occupied but pings are fine
  - nathan: feeling better, yay new volunteers, great to have new people with new takes/backgrounds
  - der.hans: great to have people from all over the planet! last year had 4 different continents on PR
  - mateus: glad to be part of community
  - ben: issue based meeting agenda has provided nice structure
  - christy: love getting to know everyone on the team, open to candid feedback
  - sNTxRr: really excited for 2nd year, may have secret tech volunteer

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

### 3/8
- [ ] SeaGL/organization#75 transition fiscal sponsorship away from the FSF
- [ ] SeaGL/organization#78 Document the new project management system (Salt)
- [ ] SeaGL/organization#79 Finalize committee descriptions (Salt)
- [ ] SeaGL/organization#80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Finance, 1x Promotion/Outreach, 1x Partnerships, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] SeaGL/organization#81 Set up asynchronous method to review feedback from last year (Salt)

### 4/19
- [x] SeaGL/organization#96 Start the conversation with the OSI about doing a 1-2 year fiscal sponsor relationship (Deb)
- [x] SeaGL/organization#97 Begin paperwork to move to OSI as a fiscal sponsor (Deb and Salt)
- [ ] SeaGL/organization#82 Create the process to pull down, transcribe, and archive 2020 videos (Don and Keith)
- [x] SeaGL/organization#85 Take an initial pass on the 2021 timeline (Rachel and Nathan)

### 5/3
- [x] SeaGL/staff#33 Copy over the old agenda norms to template (Salt)
- [ ] SeaGL/staff#34 Organize committee finance committee meeting to set next steps for FSF migration (der.hans)
- [ ] SeaGL/staff#35 Talk to programming and partnerships about what to include in 2020 gift shipments (Salt)
- [x] SeaGL/organization#102 Update Website to note we are 100% Virtual (Tech)
- [x] SeaGL/staff#37 Discuss who on the OSI board we should ask to be our sponsor (Salt and Deb)
- [ ] SeaGL/staff#38 Connect with Alison about GH issues (Salt)
- [ ] SeaGL/staff#39 Prepare 2021 Sponsor Prospectus (Finance)
- [ ] SeaGL/staff#40 Add opinions via comment on [SeaGL/organization#59](https://github.com/SeaGL/organization/issues/59) by EoD Friday (Everyone)
- [x] SeaGL/staff#41 Create issue for each committee to organize first meeting (Salt)

### Timeline

- November 5-6: SeaGL 2021

### Next Meeting
- Monday, May 31 @ 5pm PT (memorial day)
