### ISSUE TITLE
2021-06-14 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#127]
# 2021-06-14 SeaGL 2021 bi-weekly all-hands
- June 14th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/127)
- [Shared Pad](https://etherpad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Nathan
- Note Taker next meeting: 

### Metrics (previous --> current)
- Keynote nominations: 35 --> 
- (keep brainstorming!)
  - Rachel would like to see more, form is still open, keep bringing folks up! Even if you think of it during the meeting.
  - https://docs.google.com/forms/d/e/1FAIpQLSdr6ijEpmdFFkvSQEV1rS7oWsQ3Ti83xeteBuhEKJ7FsTCpVw/viewform?usp=sf_link

### Previous meeting feedback
- Nathan: in the heat of it for programming, nice to have a committee
- Norm: still looking for place to fit in and help out, preferably not as committee lead, wants to help with video transcriptions
- Hans: welcome/welcome back everyone, nice to hear the programming committee has new folks
- Ryan: going to dig through GitHub issues and see where I can help out
- Christy: looking forward to connecting offline with finance to work on prospectus and talk about sponsors, thanks to everyone for being involved
- Salt: <3
- Andrew: still confused about my task, biggest thought is that no one in charge of tech stuff re: OSEM
  - need more people power to move it forward
  - probably not upgrading OSEM this year and that's ok(?)
  - this bugs Andrew a LOT
  - Sri will introduce Don to Kenny as a sysadmin type person
- Don: pains me to hear something so neglected
- Sri: glad to be here and help out, looking forward to SeaGL 2021
- Rhiannon: glad to have something else to do and help out with
  - (Don will invite her to tech committee!)
- Deb: glad we've stopped glossing things over in terms of OSEM and enjoyed the smaller group of people 

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Finance, 1x Promotion/Outreach, 1x Partnerships, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #81 Set up asynchronous method to review feedback from last year (Salt)
- [ ] #82 Publish 2020 videos (Tech)
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/3
- [ ] #106 Talk to programming and partnerships about what to include in 2020 gift shipments (Salt)
- [ ] #110 Prepare 2021 Sponsor Prospectus (Finance and Partnerships)

### 5/17
- [ ] #122 Send instructions for everyone to help with YouTube video transcription. (Keith)
- [x] #56 Update date of [virtual announcement blog post](https://github.com/SeaGL/seagl.github.io/pull/245) and LGTM (Rachel and Ben)
- [ ] #59 Finalize and send 2021 ads to Linux Magazine (Ben)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #68 Reach out to James Mason, lead of LFNW and OSEM maintainer (Andrew)
- [ ] #69 Put out a call for more tech volunteers, especially for OSEM/Rails on social media (Outreach)
- [ ] #71 Write email to SeaGL announce list (Outreach)

### 5/31 - New TODOs
- [ ] #123 Clean-up email ratsnest
  - [ ] Gather list of various email lists and aliases
  - [ ] Send emails to chairs of any committees and ask for confirmation about list names and participants
  - [ ] Follow up with non-responders at next meeting
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [ ] #125 Transition from Freenode to Libera.Chat
  - [ ] #128 queue up social media posts about Freenode → Libera.Chat transition
  - [x] unbridge Matrix channel from Freenode (Salt)
  - [/] migrate (tombstone) Matrix channel to Seattle Matrix channel (Salt)
  - [ ] bridge Seattle Matrix channel to Libera.Chat
  - [ ] remind everyone to move and use Matrix on #SeaGL:seattlematrix.org / #SeaGL:matrix.org or IRC on Libera.Chat #SeaGL
- [x] #129 enable Team Drive for Google Org (Salt or Nathan)
- [x] add transition to OSI banking as blocker for prospectus issue (Salt)
- [x] #110 send out draft of sponsor prospectus to seagl2021@ (Finance)
- [ ] #130 select 2021 theme (Everyone)
  - [x] add previous brainstorming to this issue (Salt)

## New Items
- [ ] #131 Engage with Linux Foundation events running in Seattle, September 27-October 1

### 6/14 - New TODOs
- 

## Wrap-up
- 

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- June 15 (Tuesday)**: CFP opens
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular bi-weekly all-hands Monday, June 28 @ 5pm PT
- (add committee meetings here?)

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
New Topic: Engage with Linux Foundation events running in Seattle, September 27-October 1, https://www.linuxfoundation.org/en/press-release/the-linux-foundation-announces-open-source-summit-embedded-linux-conference-2021-will-move-from-dublin-ireland-to-seattle-washington/

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/master/meetings/2021/20210614-allhands.md
