### ISSUE TITLE
2021-06-28 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#133]
# 2021-06-28 SeaGL 2021 bi-weekly all-hands
- June 28th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/133)
- [Shared Pad](https://pad.sfconservancy.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 
- Note Taker next meeting: 

### Metrics (previous --> current)
- Keynote nominations: ??

### Previous meeting feedback
??

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Finance, 1x Promotion/Outreach, 1x Partnerships, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #81 Set up asynchronous method to review feedback from last year (Salt)
- [ ] #82 Publish 2020 videos (Tech)
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/3
- [ ] #106 Talk to programming and partnerships about what to include in 2020 gift shipments (Salt)
- [ ] #110 Prepare 2021 Sponsor Prospectus (Finance and Partnerships)

### 5/17
- [ ] #122 Send instructions for everyone to help with YouTube video transcription. (Keith)
- [ ] #59 Finalize and send 2021 ads to Linux Magazine (Ben)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #68 Reach out to James Mason, lead of LFNW and OSEM maintainer (Andrew)
- [ ] #69 Put out a call for more tech volunteers, especially for OSEM/Rails on social media (Outreach)
- [ ] #71 Write email to SeaGL announce list (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest
  - [ ] Gather list of various email lists and aliases
  - [ ] Send emails to chairs of any committees and ask for confirmation about list names and participants
  - [ ] Follow up with non-responders at next meeting
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [ ] #125 Transition from Freenode to Libera.Chat
  - [ ] #128 queue up social media posts about Freenode → Libera.Chat transition
  - [/] migrate (tombstone) Matrix channel to Seattle Matrix channel (Salt)
  - [x] bridge Seattle Matrix channel to Libera.Chat
  - [ ] remind everyone to move and use Matrix on #SeaGL:seattlematrix.org / #SeaGL:matrix.org or IRC on Libera.Chat #SeaGL
- [ ] #130 select 2021 theme (Everyone)

### 6/14
- ??
- [ ] #131 Engage with Linux Foundation events running in Seattle, September 27-October 1

### 6/28
- 

## Wrap-up
- 

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- June 15 (Tuesday)**: CFP opens
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular bi-weekly all-hands Monday, July 12 @ 5pm PT
- (add committee meetings here?)

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/master/meetings/2021/20210628-allhands.md
