### ISSUE TITLE
2021-07-12 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#134]
# 2021-07-12 SeaGL 2021 bi-weekly all-hands
- July 12th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/134)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: Rachel
- Facilitator: 
- Note Taker(s): 
- Note Taker next meeting: (not next meeting but the one after: July 26, Rachel)

### Metrics (previous --> current)
- Keynote nominations: 38
- Talk Proposals: 1 -->

### Previous meeting feedback
- Too hot!!!
- Nice to have a large turnout at these meetings
- CFP IS OUT!!!
- Loads of shared excitement

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 1x Partnerships, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #82 Publish 2020 videos (Tech)
  - [ ] write up instructions and send out sign-up spreadsheet to staff@ (Keith)
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/3
- [ ] #106 Talk to programming and partnerships about what to include in 2020 gift shipments (Salt)
- [ ] #110 Prepare 2021 Sponsor Prospectus (Finance and Partnerships)

### 5/17
- [ ] #122 Send instructions for everyone to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
  - Programming, Finance, Outreach have all had meetings
  - Attendee Experience, Partnerships, SRE/Technical, Volunteers, IDEA, and CoC still haven't
  - Volunteers and Code of Conduct need chairs, IDEA and Parternships need co-chairs
- [ ] #68 Reach out to James Mason, lead of LFNW and OSEM maintainer (Andrew)
- [ ] #69 Put out a call for more tech volunteers, especially for OSEM/Rails on social media (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [x] #125 Transition from Freenode to Libera.Chat
  - [x] #128 queue up social media posts about Freenode → Libera.Chat transition
  - [x] migrate (tombstone) Matrix channel to Seattle Matrix channel (Salt)
  - [x] bridge Seattle Matrix channel to Libera.Chat
  - [x] remind everyone to move and use Matrix on #SeaGL:seattlematrix.org / #SeaGL:matrix.org or IRC on Libera.Chat #SeaGL
- [ ] #130 select 2021 theme (Everyone)

### 6/14
- [ ] notify anyone looking to hold a "sponsored track" that they need to have one person volunteer for the conference beforehand, attending the all-hands regularly (Everyone)
- [ ] #131 Engage with Linux Foundation events running in Seattle, September 27-October 1 (Sri and Salt)

### 6/28
- [x] Follow up with Phyllis about the actual contract OSI needs to accept sponsors (Salt & Deb)
- [ ] Follow up with person who illustrates conference talks to gather information (Nathan)
- [ ] Send any similar suggestions of artists who illustrate conference talks to Nathan (everyone)
- [ ] Rip the 2020 videos and post them to archive.org and let Ben know the links when they're available for social-ing (Don)

### Moving to weekly all-hands (Salt)
- When do we want to do this? August? September?

### 7/12 - New TODOs
- [ ] 

## Wrap-up
- 

### Upcoming blog/social posts

- [x] CFP Opens
- [x] Program Committee Code of Practice
- [ ] CFP Reminder/Call for Specific Talks
- [ ] CFP Closes
- [ ] CFP Notifications
  - Nathan: Did we actually blog about this in the past?
- [ ] Final Program

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- July 12 (Monday)*: announce 2021 sponsorship opportunities
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular bi-weekly all-hands Monday, July 26 @ 5pm PT
- (add committee meetings here?)

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/master/meetings/2021/20210712-allhands.md
