### ISSUE TITLE
2021-07-26 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#135]
# 2021-07-26 SeaGL 2021 bi-weekly all-hands
- July 26th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/135)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Rachel
- Note Taker next meeting: 

### Metrics (previous --> current)
- Keynote nominations: 38
- Talk Proposals: 3 --> 
- Sponsors: 2 --> 
- Committee budgets: 0 -->

### Previous meeting feedback
- Ending with enough time for open discussion was nice
- Lots of progress being made!
- Lots of help from lots of folks!
- More to think about regarding increasing activity on IRC/blog

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #82 Publish 2020 videos (Tech)
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
  - Programming, Finance, Outreach have all had meetings
  - Partnerships has somewhat had meetings by not being fully split from Finance
  - Attendee Experience, SRE/Technical, Volunteers, IDEA, and CoC still haven't afaik
  - Volunteers and Code of Conduct need chairs, IDEA and Partnerships need co-chairs
- [ ] #69 Put out a call for more tech volunteers, especially for OSEM/Rails on social media (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [ ] #130 select 2021 theme (Everyone)

### 6/14
- [ ] notify anyone looking to hold a "sponsored track" that they need to have one person volunteer for the conference beforehand, attending the all-hands regularly (Everyone)
  - we want to put minimal effort into this at this point, it's open if someone wants to approach us
  - deadline, at latest, is when we start forming the schedule

### 6/28
- [ ] Send any similar suggestions of artists who illustrate conference talks to Nathan (everyone)

### 7/12
- [ ] post prospectus to web site (der.hans)
- [ ] setup attend.seagl.org for CFP office hours (Andrew)
- [ ] get Salt InternetArchive credentials to figure out why videos are visible (sntxrr)
- [ ] vote for keynotes, https://civs1.civs.us/cgi-bin/opt_in.pl (everyone)
- [ ] talk to Monica about sponsorship for live graphical notes (der.hans)
- [ ] add speaker gifts as an add-on (der.hans)
- [ ] all committees submit budget requests for 2021 (committee chairs)
- [ ] write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)
- [ ] review site and public documentation for fiscal sponsor updates (der.hans)

### Upcoming blog/social posts

- [x] CFP Opens
- [x] Program Committee Code of Practice
- [ ] CFP Reminder/Call for Specific Talks
- [ ] CFP Closes
- [ ] CFP Notifications
  - Nathan: Did we actually blog about this in the past?
- [ ] Final Program
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular bi-weekly all-hands Monday, August 9 @ 5pm PT
- Finance and Partnerships Thursday, August 5 @ 16:00 PT

### Sign-off round (what's next, appreciations, suggestions)
- 

# Meeting adjourned!

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/master/meetings/2021/20210726-allhands.md
