### ISSUE TITLE
2021-08-09 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#136]
# 2021-08-09 SeaGL 2021 bi-weekly all-hands
- August 9th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/136)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Don
- Note Taker next meeting: 

### Metrics (previous --> current)
- Keynote nominations: 38
- Confirmed Keynotes: 0
- Talk Proposals: 9 --> 
- Committee budgets: 0 --> 
- Sponsors: 2 --> 

### Previous meeting feedback
- Everyone please join Matrix rooms
- Looking forward to office hours
- Everyone needs to do some more broadcasting of the CFP
- Excited to see what talks we get this year
- Good folks help make everything better
- Nice to see the sausage making
- Extra thanks to note takers

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #82 Publish 2020 videos (Tech)
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #69 Put out a call for more tech volunteers, especially for OSEM/Rails on social media (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest (Salt, Tech)
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [ ] #130 select 2021 theme (Everyone)

### 6/14
- [ ] notify anyone looking to hold a "sponsored track" that they need to have one person volunteer for the conference beforehand, attending the all-hands regularly (Everyone)

### 6/28
- [x] Send any similar suggestions of artists who illustrate conference talks to Nathan (everyone)

### 7/12
- [x] post prospectus to web site (der.hans)
- [x] setup chat portal for CFP office hours (Andrew)
- [ ] #138 talk to Monica about ubuntu community fund sponsorship for live graphical notes (der.hans)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
  - sre/tech: $33.39 per month for AWS bills
- [ ] #137 write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)
- [ ] #140 review site and public documentation for fiscal sponsor updates (der.hans)

### 7/26
- [ ] #141 contact Women in Linux regarding last year's agreement (Sri, Ben)
- [ ] #142 loop Don in on conversations with Internet Archive (Salt)
- [ ] #143 reach out to friend who worked on OSEM (Sri)
- [x] review short description of virtual SeaGL at bottom of sponsor prospectus (Everyone)
- [ ] #144 decide on url attending seagl and using the rest of the year (Everyone)
- [ ] #145 update attend.seagl.org to point to seagl.org/chat, or whatever we decide should be the canonical name (Andrew)
- [ ] #146 ping various IRC channels about open CFP (Salt)
- [ ] #147 respond to Minds Eye Creative with two plans, one for keynotes only, one for whole conference, include ask about CC BY-SA (Nathan)
- [ ] #148 start brainstorming how and when a geeky fashion show would take place (Everyone)
- [ ] #149 get CFP office hours plan together (Salt)
- [ ] #150 reach out to Jupiter Broadcasting about CFP, SeaGL in general, and giving a talk (Salt, Partnerships)

### Upcoming blog/social posts

- [ ] CFP Reminder/Call for Specific Talks
- [ ] CFP Closes
- [ ] CFP Notifications
  - Nathan: Did we actually blog about this in the past?
- [ ] Final Program
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular bi-weekly all-hands: Monday, August 9 @ 5pm PT
- Programming and Flow: Tuesday, August 2 @ 17:00 PT (Off weeks from All-Hands Meetings)
- Outreach: Tuesday, August 3 @ 12:00 PT (Off weeks from All-Hands Meetings)
- Tech: Wednesday, August 4 @ 17:00 PT (Off weeks from All-Hands Meetings)
- Finance and Partnerships: Thursday, August 5 @ 16:00 PT (Off weeks from All-Hands Meetings)

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/master/meetings/2021/20210809-allhands.md
