### ISSUE TITLE
2021-08-23 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#152]
# 2021-08-23 SeaGL 2021 bi-weekly all-hands
- August 23rd, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/152)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): ???
- Note Taker next meeting: 

### Metrics (previous --> current)
- Talk Proposals: 26 --> 
- Confirmed Keynotes: 3 --> 
- Keynote nominations: 38
- Committee budgets: 0 --> 
- Sponsors: 3 --> 

### Previous meeting feedback
- Everyone was very excited about keynoters!
- Everyone was very excited about having 2020 videos up!
- Everyone needs to forward the CFP!

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #69 Put out a call for more volunteers, especially for Volunteer Lead and OSEM/Rails developer (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest (Salt, Tech)
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [ ] #130 select 2021 theme (Everyone)

### 7/12
- [ ] #138 talk to Monica about ubuntu community fund sponsorship for live graphical notes (der.hans)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
  - sre/tech: $33.39 per month for AWS bills
- [ ] #137 write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)
- [ ] #140 review site and public documentation for fiscal sponsor updates (der.hans)

### 7/26
- [ ] #143 reach out to friend who worked on OSEM (Sri)
- [ ] #148 start brainstorming how and when a geeky fashion show would take place (Everyone)
- [x] #150 reach out to Jupiter Broadcasting about CFP, SeaGL in general, and giving a talk (Salt, Partnerships)

### 8/09
- [ ] announcement about 2020 videos (Outreach)
  - blog post with links
  - social media faucet
  - combine with announcements that CFP is open
- [ ] ask personal connections to submit to CFP (Everyone)
- [ ] add language about release license to talk acceptance (Programming)
- [ ] announcement about 2021 keynotes (Outreach)

### Upcoming blog/social posts

- [ ] CFP Reminder/Call for Specific Talks
- [ ] CFP Closes
- [ ] CFP Notifications
  - Nathan: Did we actually blog about this in the past?
- [ ] Final Program
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- August 19 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular bi-weekly all-hands: Monday, September 6 @ 5pm PT

#### Off week committee meetings
- Programming and Flow: Tuesday, September 14 @ 17:00 PT
- Outreach: Tuesday, September 14 @ 12:00 PT
- Tech: Wednesday, September 15 @ 17:00 PT
- Finance and Partnerships: Thursday, September 16 @ 16:00 PT

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
New topic: Transition to weekly meetings (Salt)

**Comment by funnelfiasco** [comment]
New topic: [Press kit](https://seagl.org/press) (Ben)
