### ISSUE TITLE
2021-09-13 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#158]
# 2021-09-13 SeaGL 2021 weekly all-hands (T-8)
- September 13th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/158)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Nathan
- Note Taker next meeting: 

### Metrics (previous --> current)
- Talk Proposals: 44 --> 
- Confirmed Keynotes: 4
- Keynote nominations: 38
- Committee budgets: 0 --> 
- Sponsors: 3 --> 

### Previous meeting feedback
- Everyone was very excited about new website pages and tech update!
- Everyone was very excited about Lacey joining!

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 1x Volunteers, 1x IDEA, 2x CoC
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #69 Put out a call for more volunteers, especially for Volunteer Lead and OSEM/Rails developer (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest (Salt, Tech)
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
- [ ] #130 select 2021 theme (Everyone)

### 7/12
- [ ] #138 talk to Monica about ubuntu community fund sponsorship for live graphical notes (nathan)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
- [ ] #137 write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)
- [ ] #140 review site and public documentation for fiscal sponsor updates (der.hans)

### 7/26
- [ ] #143 reach out to friend who worked on OSEM (Sri)
- [ ] #148 start brainstorming how and when a geeky fashion show would take place (Everyone)

### 8/09
- [ ] announcement about 2020 videos (Outreach)
- [ ] add language about release license to talk acceptance (Programming)
- [ ] announcement about 2021 keynotes (Outreach)
  - Marie Nordin, Christine & Morgan Lemmer-Webber, Elana Hashman, and Cory Doctorow

### 8/23
- [ ] gather 2020 volunteer emails from Lucy, send to Lacey (hans)
- [ ] take on and contact one or more sponsors (Everyone)
  - add your name to the sheet and cc sponsors@seagl.org when taking somewhere on
  - https://docs.google.com/spreadsheets/d/1AZx2F2zmOQD-lfBdHj9YWNqvndj8lShrXjrbS43-8Es/edit
- [ ] review and provide feedback on the press kit (Everyone)
  - https://seagl.org/press
  - https://github.com/SeaGL/organization/issues/27
- [ ] review and provide feedback on the meet landing page (Everyone)
  - https://seagl.org/meet
- [ ] submit name suggestions for seagl colors (Everyone)
  - https://forms.gle/6qSQHC2HodwhDbTQ7
  - https://github.com/SeaGL/organization/issues/154

### Upcoming blog/social posts

- [ ] CFP Notifications
  - Nathan: Did we actually blog about this in the past?
- [ ] Final Program
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, September 20 @ 5pm PT

#### committee meetings
- Programming and Flow: Tuesday, September 14 @ 17:00 PT
- Outreach: Tuesday, September 14 @ 12:00 PT
- Tech: Wednesday, September 15 @ 17:00 PT
- Finance and Partnerships: Thursday, September 16 @ 16:00 PT

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by koronkowy** [comment]
To add to the agenda: https://github.com/SeaGL/organization/issues/160 Partnership verbiage update for the website, cause it's stuck in 2020.

**Comment by koronkowy** [comment]
To add to agenda: https://github.com/SeaGL/organization/issues/164
I'd like to get a request for help on transitioning FAQ docs from 2020 to 2021 on the map but this might take some time and isn't an immediate task need, but I want some visibility on it as it includes multiple committees contributions.
