### ISSUE TITLE
2021-09-20 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#168]
# 2021-09-20 SeaGL 2021 weekly all-hands (T-7)
- September 20th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/168)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Ben
- Note Taker next meeting: 

### Metrics (previous --> current)
- Remaining meetings: 6
- Committee budgets: 0 --> 
- Sponsors: 3 --> 6
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote nominations: 38

### Previous meeting feedback
- Everyone is feeling the pressure building as the weeks fly by
- Everyone is excited to push things forward and clear off checklists
- Everyone welcomes Dorian

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 1x Volunteers, 1x IDEA, 2x CoC
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #69 Put out a call for more volunteers, especially for Volunteer Lead and OSEM/Rails developer (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest (Salt, Tech)
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
  - Waiting until ~~2020 videos are up~~ and swag has shipped
- [ ] #130 select 2021 theme (Everyone)

### 7/12
- [ ] #138 talk to Monica about ubuntu community fund sponsorship for live graphical notes (nathan)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
- [ ] #137 write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)
- [ ] #140 review site and public documentation for fiscal sponsor updates (der.hans)

### 7/26
- [ ] #143 reach out to friend who worked on OSEM (Sri)
- [ ] #148 start brainstorming how and when a geeky fashion show would take place (Everyone)

### 8/09
- [ ] add language about release license to talk acceptance (Programming)
- [ ] announcement about 2021 keynotes (Outreach)

### 8/23
- [ ] gather 2020 volunteer emails from Lucy, send to Lacey (hans)
- [ ] take on and contact one or more sponsors (Everyone)
  - add your name to the sheet and cc sponsors@seagl.org when taking somewhere on
  - https://docs.google.com/spreadsheets/d/1AZx2F2zmOQD-lfBdHj9YWNqvndj8lShrXjrbS43-8Es/edit
- [ ] submit name suggestions for seagl colors (Everyone)

### 9/13
- [x] send email with poll for 2021 theme (Salt)
- [ ] get conference tabling gear from storage before OSS (Salt)
- [ ] design handbill four-to-a-page handouts for OSS (Outreach)
- [ ] print handbill four-to-a-page handouts for OSS (Salt)
- [ ] ask OSI whether they want a "booth" at seagl (Salt)
- [ ] reach out to SCC about how we can thank them (Salt)
- [ ] talk to Deb about fsf as a non-profit sponsor (Salt)

### Upcoming blog/social posts

- [ ] ASAP: Keynotes (Ben) [Rachel, Nathan]
- [ ] Final Program (Rachel, Nathan)
- [ ] SeaGL Archive site and videos (Ben)
- [ ] Request for Volunteers (Lacey)
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- Week Of ~~Aug 30~~ Sept 13 (choose w/ committee): Select Speakers
- September ~~6~~ (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, September 27 @ 5pm PT
  - Remember, _weekly_ meetings until the conference!

#### committee meetings
- Programming and Flow: Tuesday, September 28 @ 17:00 PT
- Outreach: Tuesday, September 28 @ 12:00 PT
- Tech: Wednesday, September 29 @ 17:00 PT
- Finance and Partnerships: Thursday, September 30 @ 16:00 PT

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
## New Topics


### Add staff "sponsor" orgs (Salt)
- We'd like to offer all staff the opportunity to promote one FLOSS organization they work with at the thanks level (thanks for donating your time here rather than there!)

### Budget request process (Salt)
1. the _requester_ opens an issue on GH which includes the _amount requested_ and whether there is a _deadline_
2. the _requester_ tags this issue with both the _finance committee_ and the _requesting committee_, also the _conference year_ if it is relavent
3. the _finance committee_ will review _by the next meeting_ (at the latest) and respond in the GH issue with the _decision_
4. once the purchase has been made, the _requester_ responds with the _amount to be reimbursed_ on the GH issue, which includes an @ ping to the _finance committee chair_
5. the _finance committee chair_ responds on the GH issue with the _date the reimbursement was issued_ or with a _request for more information_
6. the _requester_ closes the GH issue once the reimbursement has _been received_

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/main/meetings/2021/20210920-allhands.md
