### ISSUE TITLE
2021-09-27 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#181]
# 2021-09-27 SeaGL 2021 weekly all-hands (T-6)
- September 27th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/181)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: Deb
- Note Taker(s): Rachel
- Note Taker next meeting: 

### Metrics (previous --> current)
- Remaining meetings: 5
- Sponsors: 6 --> 
- Committee budgets: 2 --> 
- Confirmed Talks: ~17 -->
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote nominations: 38

### Previous meeting feedback
- Excited for dry run, program, party games, sponsors, checked off lists
- Feeling less hectic/panicked than last year
- Good meeting

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 1x Volunteers, 2x IDEA
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [ ] #69 Put out a call for more volunteers, especially for Volunteer Lead and OSEM/Rails developer (Outreach)

### 5/31
- [ ] #123 Clean-up email ratsnest (Salt, Tech)
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
  - Waiting until ~~2020 videos are up~~ and swag has shipped
- [ ] #130 select 2021 theme (Everyone)

### 7/12
- [ ] #138 submit the request to Ubuntu community fund for sponsorship of live graphical notes (Nathan)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
- [ ] #137 write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)
  - holding off at least until we become an incubator project
- [ ] #140 review site and public documentation for fiscal sponsor updates (der.hans)

### 7/26
- [ ] #148 start brainstorming how and when a geeky fashion show would take place (Everyone)

### 8/09
- [ ] #169 announcement about 2021 keynotes (Outreach)

### 8/23
- [ ] take on and contact one or more sponsors (Everyone)
  - add your name to the sheet and cc sponsors@seagl.org when taking somewhere on
  - https://docs.google.com/spreadsheets/d/1AZx2F2zmOQD-lfBdHj9YWNqvndj8lShrXjrbS43-8Es/edit
  - time to bump threads that haven't yet been responded to
- [ ] #154 submit name suggestions for seagl colors (Everyone)
  - Keep bumping on social media

### 9/13
- [ ] #182 table at OSS
  - [ ] get conference tabling gear from storage before OSS (Salt)
  - [ ] design handbill four-to-a-page handouts for OSS (Outreach)
  - [ ] print handbill four-to-a-page handouts for OSS (Salt)
- [x] ask OSI whether they want a "booth" at seagl (Salt)
- [x] reach out to SCC about how we can thank them (Salt)

### 9/20
- [ ] reach out to Dorian to ask if he wants to be considered Volunteers Chair 2 (Lacey)
- [ ] connect with Lacey to print labels for 2020 swag (Salt)
- [x] update budget issue with checkbox list of committees to keep track of who has/hasn't sent theirs in (Salt)
- [x] do some grepping of the website repo for outdated FSF info (der.hans, Salt)
  - looks like two lines will need to be changed, but right now the info is not visible
  - https://github.com/SeaGL/seagl.github.io/blob/main/index.html#L71
  - https://github.com/SeaGL/seagl.github.io/blob/main/_config.yml#L106
- [x] set up small group chat for folks tabling OSS [Sri, Salt, Lacey] (Salt)
- [ ] reach out DevOpsDays PDX about running games on Saturday (Rachel)
- [ ] look into why emails are going to spam (Tech)
- [ ] explore options for 1-to-many emails, e.g., sendgrid (Tech)

### CoC revision (Lacey)
- https://github.com/SeaGL/organization/issues/180
- https://github.com/SeaGL/organization/blob/main/Code-of-Conduct.md

### Upcoming blog/social posts

- [ ] ASAP: Keynotes (Ben) [Rachel, Nathan]
- [ ] Final Program (Rachel, Nathan)
- [ ] SeaGL Archive site and videos (Ben)
- [ ] Request for Volunteers (Lacey)
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- Week of September 20: Full tech run-through of technologies at Tech Meeting
- Week of September 27: Documentation run-through of technologies at Tech Meeting
- October 1st ~~September 20 (Monday)~~: Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- October 8th ~~September 27 (Monday)~~*: Finalize Program
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, October 4 @ 5pm PT
  - Remember, _weekly_ meetings until the conference!

#### Committee Meetings
- Programming and Flow: Tuesday, October 5 @ 17:00 PT
- Outreach: Tuesday, October 5 @ 12:00 PT
- Tech: Wednesday, September 29 @ 17:00 PT
- Finance and Partnerships: Monday, September 20 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by koronkowy** [comment]
If you could please add CoC revision to the agenda : https://github.com/SeaGL/organization/issues/180

**Comment by dorian-wood** [comment]
Added CoC revision and moderation as tasks for 9/27

**Comment by altsalt** [comment]
Thanks @koronkowy and @dorian-wood I've aligned formatting.

Just an FYI for everyone, due to uncertainty around availability at OSS, I've asked Deb to facilitate this week's meeting.

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/main/meetings/2021/20210927-allhands.md
