### ISSUE TITLE
2021-10-04 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#187]
# 2021-10-04 SeaGL 2021 weekly all-hands (T-5)
- October 4th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/186)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Norm
- Note Taker next meeting: der.hans
- Note Taker next next meeting: 

### Metrics (previous --> current)
- Remaining meetings: 4
- Sponsors: 11 --> 
- Committee budgets: 2 --> 
- Confirmed Talks: ~19 --> 
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote nominations: 38

### Previous meeting feedback
- not captured

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [x] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
  - We are officially an OSI incubator project!!!
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 2x IDEA
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [ ] #69 Put out a call for more volunteers (Lacey)

### 5/31
- [ ] #124 Close out 2020, that list in the corner we never look at...
  - https://github.com/SeaGL/organization/projects/1
  - [x] Post 2020 videos
  - [ ] Ship 2020 swag
- [ ] #130 select 2021 theme (Everyone)
  - To be selected... at this meeting!

### 7/12
- [ ] #138 request ubuntu community fund sponsorship for live graphical notes (Nathan)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
- [ ] #137 write post about becoming incubator project, give background about fiscal sponsors, vision of future (Salt)

### 7/26
- [ ] #148 start brainstorming how and when a geeky fashion show would take place (Everyone)
  - time slot: ???

### 8/23
- [ ] take on and contact one or more sponsors (Everyone)
  - add your name to the sheet and cc sponsors@seagl.org when taking somewhere on
  - https://docs.google.com/spreadsheets/d/1AZx2F2zmOQD-lfBdHj9YWNqvndj8lShrXjrbS43-8Es/edit
  - time to bump threads that haven't yet been responded to
- [ ] name seagl colors (Everyone)

### 9/13
- [ ] ask OSI whether they want a "booth" at seagl (Salt, Deb)

### 9/20
- [ ] connect with Lacey to print labels for 2020 swag (Salt)
- [ ] reach out DevOps Games about running games on Saturday (Rachel)
  - will be trying to DM them instead of the email, no response yet
- [ ] look into why emails are going to spam (Tech)

### 9/27
- [x] add graphical notes to sponsor prospectus and agreement (der.hans)
- [ ] respond to FSF about booth (der.hans)
- [ ] read and review CoC revisions (Deb and Dorian)
- [ ] schedule meeting with Lacey, Dorian & Don for CoC & moderation rules/processes (Rachel)
- [ ] create Github issue for brainstorming digital gifts to speakers (der.hans)

### Upcoming blog/social posts

- [ ] Final Program (Rachel, Nathan)
- [ ] SeaGL Archive site and videos (Ben)
- [ ] Request for Volunteers (Lacey)
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- Week of September 20: Full tech run-through of technologies at Tech Meeting
- Week of September 27: Documentation run-through of technologies at Tech Meeting
- October 1st ~~September 20 (Monday)~~: Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- October 8th ~~September 27 (Monday)~~*: Finalize Program
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, October 4 @ 5pm PT
  - Remember, _weekly_ meetings until the conference!

#### Committee Meetings
- Programming and Flow: Tuesday, October 5 @ 17:00 PT
- Outreach: Tuesday, October 5 @ 12:00 PT
- Tech: Wednesday, September 29 @ 17:00 PT
- Finance and Partnerships: Monday, September 20 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/main/meetings/2021/20211004-allhands.md
