### ISSUE TITLE
2021-10-11 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#192]
# 2021-10-11 SeaGL 2021 weekly all-hands (T-4)
- October 11th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/192)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: Salt
- Note Taker(s): der.hans
- Note Taker next meeting: ???
- Note Taker next next meeting: ???

### Metrics (previous --> current)
- Remaining meetings: **3**
- Sponsors: 11 --> 
- Committee budgets: 2 --> 
- Confirmed Talks: ~39 --> 
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote nominations: 38

### Previous meeting feedback
- This year is feeling less stressful, more organized
- Excited about all of the work going on

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 1x Partnerships, 2x IDEA
- [ ] #83 Ship 2020 speaker swag (Salt)
  - have shipping labels, was out of town this weekend and PO closed today, but this week!

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)
- [x] #69 Put out a call for more volunteers (Lacey)
  - https://seagl.org/news/2021/10/05/volunteers-2021.html

### 7/12
- [ ] #138 request ubuntu community fund sponsorship for live graphical notes (Nathan)
  - request was submitted and approved
  - next steps is to send them information to process a money transfer
  - they'll need to fill out the sponsorship interest form, where we'll get the proper logo and such
  - [ ] connect ubuntu community fund and OSI for account details (Finance)
- [ ] #139 all committees submit budget requests for 2021 (committee chairs)
  - still looking for: Finance, Partnerships, Volunteers, IDEA, CoC
- [ ] #137 write post about becoming OSI incubator project (Salt, Deb, Ben)
  - to include background about previous fiscal sponsors and future vision of seagl org

### 7/26
- [ ] #148 plan geeky fashion show (Attendee Experience)
  - time slot: ??

### 8/23
- [ ] #154 name SeaGL colors via community poll (Outreach)
  - Suggestions form: https://forms.gle/6qSQHC2HodwhDbTQ7
  - Suggestions poll will close on friday week before seagl, voting will open monday of seagl week

### 9/13
- [x] ask OSI whether they want a "booth" at seagl (Deb)

### 9/20
- [x] connect with Lacey to print labels for 2020 swag (Salt)
- [ ] reach out DevOps Games about running games on Saturday (Rachel)

### 9/27
- [ ] respond to FSF about booth (der.hans)
- [x] create Github issue for brainstorming digital gifts to speakers (der.hans)
  - [ ] #188 brainstorm 2021 speaker gifts (Everyone)

### 10/04
- [ ] Blog post to announce that SeaGL is part of OSI (Deb, Salt, Ben)
  - think this is the same as #137
- [x] send call for volunteers blog post tomorrow (Lacey)
- [ ] email with shareable link to seagl2021, ambassador, etc (Lacey)
- [x] discuss theme in this week's meeting (Outreach)
- [ ] add $150 budget request for tea from AX (Finance)
- [ ] #148 nail down details around geeky fashion show (Attendee Experience)
  - combined details into 7/26 issue above
- [ ] draft announcement that color suggestions poll will close on friday week before seagl, voting will open monday of seagl week (Outreach)
  - part of #154
- [ ] put response to FSF in pad and share to seagl2021 (der.hans)
- [x] #190 Draft Social/Blog post about new CoC then request for feedback/comment (Outreach, Ben)
  - https://github.com/SeaGL/seagl.github.io/pull/285
- [x] loop deb and finance into OSI sponsorship link conversation (Salt)
  - had good call, ironed out details, ready to send to sponsors

### 10/11 - New TODOs
- [ ] connect ubuntu community fund and OSI for account details (Finance)
- [ ] #188 brainstorm 2021 speaker gifts (Everyone)

### Upcoming blog/social posts

- [ ] Final Program (Rachel, Nathan)
- [ ] SeaGL Archive site and videos (Ben)
- [ ] Request for Volunteers (Lacey)
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt, Deb)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- Week of October 4 ~~September 20~~: Full tech run-through of technologies at Tech Meeting
  - ran through speaker side, not participant
  - will at wednesday meeting (how things flow, decisions)
  - Next week (participant focus first, split up tracks, email) Documentation
- Week of October 8 ~~September 27~~: Documentation run-through of technologies at Tech Meeting
- ~~October 1st~~ ~~September 20~~ ~~(Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]~~
- October 8th ~~September 27~~ (Monday)*: Finalize Program
- Weeks of October 18 & October 25: Tech training for volunteers
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, October 11 @ 5pm PT
  - Remember, _weekly_ meetings until the conference!

#### Committee Meetings
- Programming and Flow: Tuesday, October ?? @ 17:00 PT
- Outreach: Tuesday, October ?? @ 12:00 PT
- Tech: Wednesday, October ?? @ 17:00 PT
- Finance and Partnerships: Monday, October 11 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/main/meetings/2021/20211011-allhands.md
