### ISSUE TITLE
2021-10-18 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#193]
# 2021-10-18 SeaGL 2021 weekly all-hands (T-3)
- October 18th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/193)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Ben
- Note Taker penultimate meeting: Don/sntxrr
- Note Taker meeting finale: 

### Metrics (previous --> current)
- Remaining meetings: **_2_**
- Sponsors: 9 --> 
- Committee budgets: 5 --> 
- Confirmed Talks: 39
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote nominations: 38

### Previous meeting feedback
- Yay, such a good team of new and old volunteers!
- Stuff is getting done and short meetings are good
- Can't believe we're so close!

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 2x IDEA
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/17
- [ ] #122 Send instructions for staff@ to help with YouTube video transcription. (Keith)

### 7/12
- [ ] #137 write post about becoming OSI incubator project (Salt, Deb, Ben)

### 7/26
- [ ] #148 plan geeky fashion show (Attendee Experience)

### 8/23
- [ ] #154 name SeaGL colors via community poll (Outreach)
  - Suggestions form: https://forms.gle/6qSQHC2HodwhDbTQ7
  - Suggestions poll will close on friday week before seagl, voting will open monday of seagl week

### 9/20
- [ ] reach out DevOps Games about running games on Saturday (Rachel)

### 9/27
- [ ] respond to FSF about booth (der.hans)

### 10/4
- [ ] email with shareable link to seagl2021, ambassador, etc (Ben)
- [ ] add $150 budget request for tea from AX (Finance)

### 10/11
- [ ] connect ubuntu community fund and OSI for account details (Finance, Salt)
  - related to #138
- [ ] updated poll with nameless color images (Salt)
  - related to #154
- [ ] #188 brainstorm 2021 speaker gifts (Everyone)
- [ ] schedule time to talk to deb and ben for first draft of OSI announcement (Salt)
- [ ] update ~~fb event~~, website, etc with theme text (Salt)
  - related to #130
- [ ] connect with AX committee for update about fashion show and teagl timing (Salt)
  - related to #148
- [ ] review and revise response to fsf regarding virtual booth (Everyone interested, Salt, Deb)
  - see email titled, "draft response about FSF booth" on 10/11
- [ ] review and revise new CoC blog post by 10/12 (soft), 10/15 (hard) (Everyone)
  - https://github.com/SeaGL/seagl.github.io/pull/285

### Upcoming blog/social posts

- [ ] Final Program (Rachel, Nathan)
- [ ] SeaGL Archive site and videos (Ben)
- [ ] Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt, Deb, Ben)
- [ ] Announcement that color suggestions poll will close on friday week before seagl, voting will open monday of seagl week (Ben)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- ~~October 8~~ ~~1st~~ ~~September 20~~ ~~(Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]~~
- Week of October 11 ~~4~~ ~~September 20~~: Full tech run-through of technologies at Tech Meeting
- Week of October 18 ~~11~~ ~~September 27~~: Documentation run-through of technologies at Tech Meeting
- October 15~~8~~th ~~September 27~~ (Monday)*: Finalize Program
- Weeks of October 18 & October 25: Tech training for volunteers
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, October 25 @ 5pm PT
  - Remember, _weekly_ meetings until the conference!

#### Committee Meetings
- Programming and Flow: Tuesday, October 19 @ 17:00 PT
- Outreach: Tuesday, October 19 @ 12:00 PT
- Tech: Wednesday, October 20 @ 17:00 PT
- Finance and Partnerships: Monday, October 18 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!
