### ISSUE TITLE
2021-10-25 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#197]
# 2021-10-25 SeaGL 2021 weekly all-hands (T-2)
- October 25th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/197)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): Don/sntxrr
- Note Taker meeting finale: 

### Metrics (previous --> current)
- Remaining Meetings: !! **_1_** !!
- Sponsors: 10 --> 
- Committee Budgets: 5
- Confirmed Talks: 39
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote Nominations: 38

### Previous meeting feedback
- ALMOST THERE!!!
- <3 Everyone
- If any group could pull this off, it's us!
- Still plenty to do, pressure cooker time
- Excited to see how everything goes

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Promotion/Outreach, 2x IDEA
- [ ] #83 Ship 2020 speaker swag (Salt)

### 7/12
- [ ] #137 write post about becoming OSI incubator project (Salt, Deb, Ben)
  - 10/20: Draft written, https://etherpad.seattlematrix.org/p/seagl-osi

### 8/23
- [ ] #154 name SeaGL colors via community poll (Outreach)
  - Suggestions form: https://forms.gle/6qSQHC2HodwhDbTQ7
  - Suggestions poll will close on friday week before seagl (29 Oct), voting will open monday of seagl week

### 9/20
- [ ] reach out DevOps Games about running games on Saturday (Rachel)

### 9/27
- [x] respond to FSF about booth (der.hans)

### 10/4
- [ ] create GH ticket to document $150 budget request for tea from AX (der.hans)

### 10/11
- [x] connect ubuntu community fund and OSI for account details (Finance, Salt)
- [x] updated poll with nameless color images (Salt)
  - related to #154
- [ ] #188 brainstorm 2021 speaker gifts (Everyone)
- [ ] schedule time to talk to deb and ben for first draft of OSI announcement (Salt)
- [x] connect with AX committee for update about fashion show and teagl timing (Salt)
- [x] review and revise response to fsf regarding virtual booth (Everyone interested, Salt, Deb)
  - see email titled, "draft response about FSF booth" on 10/11 (I think this is a duplicate? see 9/27 above)
- [x] review and revise new CoC blog post by 10/12 (soft), 10/15 (hard) (Everyone)
  - https://github.com/SeaGL/seagl.github.io/pull/285
  - to be merged 10/19 unless significant feedback comes in

### 10/18
- [ ] ask remy about doing promo/outreach (or being a co-chair) (Rachel/Nathan)
- [ ] add social events to osem, using the "dummy" user, then send the higlights to Ben in a blog form for posting and tweeting (Deb)
- [ ] update the color selection form with the new color images (Salt)
- [ ] discuss booth crawl hour on friday (Finance/Partnerships)
- [ ] send suggestions for co-trivia runner to Deb (Everyone)
- [ ] generate URLs for talks and send to Program Committee (Tech)
- [ ] review draft of documentation for speakers on streamyard, https://github.com/SeaGL/organization/pull/194/files (Programming, Tech, Volunteering)
- [ ] forward details (how to, requirements, deadline) about pre-recording to speakers details to be forwarded (Programming)
- [x] sign agreement for graphical recordings (Salt)
- [ ] send speaker images to Ben for social posting (Programming)
- [x] plan virtual volunteer thank you event post-event (but not the day after) (Salt)
- [ ] add your other FLOSS org you volunteer with as thanks-sponsor on #189 (Everyone)

### Upcoming blog/social posts

- [x] Final Program (Rachel, Nathan)
- [x] 10/19: CoC update (Ben)
- [ ] approx 10/22 SeaGL theme (Ben)
- [ ] approx 10/26 Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt, Deb, Ben)
  - Or maybe we could post it during the event as a big announcement thing. Invite Stefano to show up and talk for a few minutes to say how excited OSI is
- [ ] Social events (Deb, Ben)
- [ ] Announcement that color suggestions poll will close on friday week before seagl, voting will open monday of seagl week (Ben)
- [ ] (probably post-event) SeaGL Archive site and videos (Ben)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- ~~October 8~~ ~~1st~~ ~~September 20~~ ~~(Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]~~
- ~~October 15~~ ~~8~~th ~~September 27~~ ~~(Monday)*: Finalize Program~~
- Week of October 11 ~~4~~ ~~September 20~~: Full tech run-through of technologies at Tech Meeting
- Week of October 18 ~~11~~ ~~September 27~~: Documentation run-through of technologies at Tech Meeting
- Weeks of October 18 & October 25: Tech training for volunteers
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- Next regular weekly all-hands: Monday, November 1 @ 5pm PT
  - This is the LAST meeting before the conference!!!

#### Committee Meetings
- Programming and Flow: Tuesday, October 26 @ 17:00 PT
- Outreach: Tuesday, October 26 @ 12:00 PT
- Tech: Wednesday, October 27 @ 17:00 PT
- Finance and Partnerships: Monday, October 25 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!
