### ISSUE TITLE
2021-11-01 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#198]
# 2021-11-01 SeaGL 2021 weekly all-hands (T-1)
- November 1st, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/198)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 

### Metrics (previous --> current)
- Remaining Meetings: !! **_0_** !!
- Sponsors: 13 --> 
- Committee Budgets: 5
- Confirmed Talks: 39
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote Nominations: 38

### Previous meeting feedback
- All of the appreciation
- Consider holding staff meetings in Matrix
- Nearly there...
- Less freaked out than last year
- Everyone needs a matrix account

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [x] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - Mateus as outreach co-lead, Lacey as CoC co-lead
  - We really need to spend extra time on IDEA next year...
- [ ] #83 Ship 2020 speaker swag (Salt)

### 7/12
- [ ] #137 write post about becoming OSI incubator project (Salt, Deb, Ben)
  - 10/20: Draft written, https://etherpad.seattlematrix.org/p/seagl-osi

### 8/23
- [ ] #154 name SeaGL colors via community poll (Outreach)
  - Voting form: 

### 9/20
- [ ] reach out DevOps Games about running games on Saturday (Rachel)

### 10/4
- [ ] create GH ticket to document $150 budget request for tea from AX (der.hans)

### 10/11
- [ ] #188 brainstorm 2021 speaker gifts (Everyone)
- [ ] schedule time to talk to deb and ben for first draft of OSI announcement (Salt)

### 10/18
- [ ] add social events to osem, using the "dummy" user, then send the higlights to Ben in a blog form for posting and tweeting (Deb)
- [ ] generate URLs for talks and send to Program Committee (Tech)
- [ ] review draft of documentation for speakers on streamyard, https://github.com/SeaGL/organization/pull/194/files (Programming, Tech, Volunteering)
- [ ] forward details (how to, requirements, deadline) about pre-recording to speakers details to be forwarded (Programming)
- [ ] plan virtual volunteer thank you event post-event (but not the day after) (Salt)
- [ ] add your other FLOSS org you volunteer with as thanks-sponsor on #189 (Everyone)

### 10/25
- [ ] ask Minds Eye about additional characturer at bulk-rate add-on (Nathan)
- [ ] generate the speakers associated Matrix room (hopefully) before speaker email goes out (Tech)
- [ ] create spreadsheet to track speaker Mastadon/Twitter handles (Nathan)
- [ ] write up a doc to take a quick pass at moderation decision making (CoC)
- [ ] brainstorm Friday afternoon booth crawl (Attendee Experience)
- [ ] create ad-roll (Romeo)
- [ ] schedule a pre-conference staff meeting (Salt)

### Upcoming blog/social posts

- [ ] approx 10/22 SeaGL theme (Ben)
- [ ] approx 10/26 Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt, Deb, Ben)
  - Or maybe we could post it during the event as a big announcement thing. Invite Stefano to show up and talk for a few minutes to say how excited OSI is
- [ ] Social events (Deb, Ben)
- [ ] Announcement that color suggestions poll will close on friday week before seagl, voting will open monday of seagl week (Ben)
- [ ] (probably post-event) SeaGL Archive site and videos (Ben)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- ~~October 8~~ ~~1st~~ ~~September 20~~ ~~(Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]~~
- ~~October 15~~ ~~8~~th ~~September 27~~ ~~(Monday)*: Finalize Program~~
- Week of October 11 ~~4~~ ~~September 20~~: Full tech run-through of technologies at Tech Meeting
- Week of October 18 ~~11~~ ~~September 27~~: Documentation run-through of technologies at Tech Meeting
- Weeks of October 18 & October 25: Tech training for volunteers
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- SeaGL!!! Friday and Saturday, November 5th & 6th

#### Committee Meetings
- Programming and Flow: Tuesday, November 2 @ 17:00 PT
- Outreach: Tuesday, November 2 @ 12:00 PT
- Tech: Wednesday, November 3 @ 17:00 PT
- Finance and Partnerships: Monday, November 1 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by koronkowy** [comment]
If possible to add to the agenda, anyone involved with CoC / moderation stuff if they could take a look at the text document I shared in SeaGL staff chat that would be great, to add things we are missing, and to help choose appropriate interactions.

I'll probably flesh out more of a guide but I'd like others to help with this still.
