### ISSUE TITLE
2021-11-08 Optional All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#210]
# 2021-11-08 Post SeaGL 2021 optional all-hands
- November 8th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/210)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 

### Metrics (final 2021 numbers)
- Sponsors: 
- Confirmed Talks: 39
- Talk Proposals: 46
- Confirmed Keynotes: 4
- Keynote Nominations: 38

### Previous meeting feedback
- Feeling tired, but we're almost there!
- Crunch time! Strategic use of every hour
- Impressive task being accomplished by an impressive team
- Lots of appreciation for being able to take part
- Lots of TODOs behind us, organizational work++
- Worth running a cross-country conference to work with y'all
- SeaGL is a bright point in the year that other events can be relative to
- Much <3

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #83 Ship 2020 speaker swag (Salt)

### 7/12
- [ ] #137 write post about becoming OSI incubator project (Salt, Deb, Ben)
  - 10/20: Draft written, https://etherpad.seattlematrix.org/p/seagl-osi
  - 11/1: No time to work on it yet

### 8/23
- [ ] #154 name SeaGL colors via community poll (Outreach)
  - Voting form: https://forms.gle/ZD8pHVgZKUFwjz3r9

### 10/11
- [ ] schedule time to talk to deb and ben for first draft of OSI announcement (Salt)
  - 11/1: No update.

### 10/18
- [ ] review draft of documentation for speakers on streamyard (Programming, Tech, Volunteering)
  - https://github.com/SeaGL/organization/pull/194/files
  - TODO at Tech meeting / Dry Run
- [ ] #212 plan virtual volunteer thank you event post-event (but not the day after) (Salt)
- [x] add your other FLOSS org you volunteer with as thanks-sponsor on #189 (Everyone)

### 10/25
- [-] generate the speakers associated Matrix room (hopefully) before speaker email goes out (Tech)
- [x] write up a doc to take a quick pass at moderation decision making (CoC)
- [-] brainstorm Friday afternoon booth crawl (Attendee Experience)
- [ ] #174 create ad-roll (Mateus, Romeo)
- [x] schedule a pre-conference staff meeting (Salt)

### 11/01
- [x] Open a new issue to handle the speaker gifts (Salt)
  - https://github.com/SeaGL/organization/issues/214
- [x] Send out a scheduling poll for virtual volunteer thank you event (Salt)
- [ ] discuss interactive social event rooms (Tech)
- [ ] Add info for social events to interstitial GH issue (Deb)
- [ ] Have conversation about moderation decision making in the Triage channel (CoC, Tech)
- [x] Create an issue for any last-minute sponsor booth crawl ideas (Salt)
  - https://github.com/SeaGL/organization/issues/213
- [x] provide list of sponsors to include in ad-roll (Partnerships)
- [x] schedule a pre-conference staff meeting (Salt)
  - [ ] Invite other speaker wrangler volunteers (Lacey)
- [x] Create a seagl.org address for Mateus (Salt)
- [ ] #215 Plan what announcements need to occur and when (Salt, Programming, Partnerships, AX, Everyone)
- [x] Put the meetings on the calendar (Salt)

## Open discussion (~5 minute, if time)
- Har...

### Upcoming blog/social posts

- [ ] approx 10/26 Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt, Deb, Ben)
  - Or maybe we could post it during the event as a big announcement thing. Invite Stefano to show up and talk for a few minutes to say how excited OSI is
- [ ] (probably post-event) SeaGL Archive site and videos (2021 and 2020) (Ben)
- [ ] Speakers and sponsor thank you
- [ ] please keep an eye out for links to add to the Social post (Deb and Monica to send to Ben)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- ~~October 8~~ ~~1st~~ ~~September 20~~ ~~(Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]~~
- ~~October 15~~ ~~8~~th ~~September 27~~ ~~(Monday)*: Finalize Program~~
- Week of October 11 ~~4~~ ~~September 20~~: Full tech run-through of technologies at Tech Meeting
- Week of October 18 ~~11~~ ~~September 27~~: Documentation run-through of technologies at Tech Meeting
- Weeks of October 18 & October 25: Tech training for volunteers
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- SeaGL 2021 retrospective: Monday, November 15 @ 5pm PT 

#### Committee Meetings
- Programming and Flow: N/A
- Outreach: Tuesday, November 16 @ 12:00 PT
- Tech: 
- Finance and Partnerships: Monday, November 8 @ 18:00 PT, after all-hands

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!
