### ISSUE TITLE
2021-11-15 Retrospective

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#211]
# 2021-11-15 SeaGL 2021 retrospective all-hands
- November 15th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/211)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2021_retrospective)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 

### Metrics (final 2021 numbers)
- Staff: 
- Volunteers: 
- Registrations:
  - number of "attendees" (onsite, off, etc.): 
  - number of folks using ephemeral server: 
- Social Shares: 
- Blog Posts: 
- TeaGL Signups: 
- Career Expo Sessions:
- Career Expo Counselors:
- Ambassadors: 
- Sponsors: 34
- Fiscal Sponsors: 17
- Confirmed Speakers: 
- Confirmed Talks: 39
- Accepted Talks: 
- Speakers Submitted: 
- Talk Proposals: 46
- Office Hours Attended:
- Confirmed Keynotes: 4
- Keynote Nominations: 38
- Anything else?

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda
- Reminder: focus is on the 2021 retrospective, not 2022

#### 3/8
- [ ] #83 Ship 2020 speaker swag (Salt)

#### 7/12
- [ ] #137 write post about becoming OSI incubator project (Salt, Deb, Ben)
  - 10/20: Draft written, https://etherpad.seattlematrix.org/p/seagl-osi
  - 11/1: No time to work on it yet

#### 10/11
- [ ] schedule time to talk to deb and ben for first draft of OSI announcement (Salt)
  - 11/1: No update.

#### 10/18
- [ ] #212 plan virtual volunteer thank you event post-event (but not the day after) (Salt)
  - Please fill out availability: https://whenisgood.net/wqgrpyy

#### 11/01
- [ ] Have conversation about moderation decision making in the Triage channel (CoC, Tech)

#### 11/08
- [ ] coordinate with outreach to maximize seagl social shares before sending talk illustrations (programming)
- [ ] decide whether we are sharing raw videos with speakers (programming)
- [ ] get eta for actual editted videos (tech)
- [ ] create method to share raw videos, potentially using hans nextcloud (sntxrr)
- [ ] make call about how to handle more sales-y talks (programming)
- [ ] review of all graphical recordings (everyone)
- [ ] setup a Nextcloud instance for sharing out the raw, and later post processed videos (sntxrr)
- [ ] Make a mockup of the cards and give to Nathan (Mateus)
- [ ] Talk to Romeo to see if he can work on it. (Salt)
- [ ] update title card generator and make one for each video (Nathan)
- [ ] open issue about automating capture of metrics (Salt)
- [ ] create a task/planning list of everything that needs to be done, then work backwards.
- [ ] Generate initial spreadsheet to capture list of people/volunteers/committees that will get these. (Lacey)

### Feedback Form Review
- Process:
  - Salt will screenshare and go through the responses
  - Each response will be discussed
  - Relevant feedback will be captured below

---

### Committee Additions
- Process:
  - Each committee should go through how they felt things went and add any specific suggestions of things to consider from their committee's context
  - The group will decide what we is be called toDONE, bikeshed'ed, or what we tWONTdo
  - new TODOs should be added to the above list

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

##### Important Links

---

### Upcoming blog/social posts

- [ ] approx 10/26 Becoming OSI incubator project, give background about fiscal sponsors, vision of future (Salt, Deb, Ben)
  - Or maybe we could post it during the event as a big announcement thing. Invite Stefano to show up and talk for a few minutes to say how excited OSI is
- [ ] (probably post-event) SeaGL Archive site and videos (2021 and 2020) (Ben)
- [ ] Speakers and sponsor thank you
- [ ] please keep an eye out for links to add to the Social post (Deb and Monica to send to Ben)

### Timeline
- ~~May 10 (Monday)*: Launch Keynote request for nominations~~
- ~~May 24 (at the earliest): Close Keynote nominations~~
- ~~June~~ ~~15~~ 24 ~~(Tuesday)**: CFP opens~~
- ~~July 12 (Monday)*: announce 2021 sponsorship opportunities~~
- ~~August 19 (Thursday)*: CFP closes~~
- ~~Week Of Aug 23 (choose w/ committee): CFP Review 1~~
- ~~Week Of~~ ~~Aug 30~~ ~~Sept 13 (choose w/ committee): Select Speakers~~
- ~~September~~ ~~6~~ ~~(Monday)*: Notify Speakers~~
- ~~October 8~~ ~~1st~~ ~~September 20~~ ~~(Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]~~
- ~~October 15~~ ~~8~~th ~~September 27~~ ~~(Monday)*: Finalize Program~~
- Week of October 11 ~~4~~ ~~September 20~~: Full tech run-through of technologies at Tech Meeting
- Week of October 18 ~~11~~ ~~September 27~~: Documentation run-through of technologies at Tech Meeting
- Weeks of October 18 & October 25: Tech training for volunteers
- October 31-Nov 1: Pre-recorded talk videos in the hands of SeaGL, and they work (in VLC)!
- November 5-6 (Friday/Saturday)***: SeaGL 2021

`* means a blog post accompanies`  
`** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open`

### Next Meeting
- SeaGL 2022 Kick-off: ??

#### Committee Meetings
- Programming & Flow: N/A
- Finance and Partnerships: Monday, November 15 @ 18:00 PT, after all-hands
- Attendee Experience: N/A
- Promotion & Outreach: Tuesday, November 16 @ 12:00 PT
- SRE/Technical: ??
- Volunteers: ??
- IDEA: N/A
- CoC: N/A

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!
