### ISSUE TITLE
Migration to upstream OSEM

### ISSUE THREAD

**Issue by AndrewKvalheim** [SeaGL/organization#228]
## Rationale

See https://github.com/SeaGL/osem/issues/22.

## Roadmap

- [x] Stabilize upstream OSEM.
    - Outlined in [`AndrewKvalheim:future`][AndrewKvalheim:future]
- [x] Deploy a trial instance of upstream OSEM with SeaGL's data.
    - SeaGL/osem#29
- [x] Review functionality of the trial instance and develop any necessary software modifications.
    - There are still a few modifications to make but nothing blocking migration.
- [x] Migrate production instance to upstream OSEM.

## Open questions

- [x] How is this affected by migration to OSU OSL infrastructure?
    - Decoupled; we’ve continued to deploy to AWS for now but have designed for ease of later migration.

[AndrewKvalheim:future]: https://github.com/AndrewKvalheim/osem/tree/future#readme
