### ISSUE TITLE
2022-04-05 All-Hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#249]
# 2022-04-05 SeaGL 2022 All-Hands
- April 5, 2022. 1800 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/249)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2022_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2022_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/tree/main/meetings/2022)
- [Mailing list](https://groups.google.com/a/seagl.org/g/seagl2022)
- [2021 Retrospective](https://github.com/SeaGL/organization/blob/main/meetings/2021/20211115-retrospective.md)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): J
- Note Taker(s) for next time: 

### Metrics - not tracking at this time
- Staff: 
- Ambassadors: 
- Social Shares: 
- Blog Posts: 
- Sponsors: 
- Keynote Nominations:

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 02/08
- [ ] invite a friend to participate (*everyone*)
  - Going to keep this on until Salt feels like it and/or we have chairs for each committee
- [ ] #222 review retrospective by next meeting (everyone)
  - Each committee should complete this task at their first meeting.
- [ ] #245 review web site for needed updates by next meeting (everyone)
  - Each committee should complete this task at their first meeting.
- [ ] reach out to media sponsors and Ambassadors list about planning, filling chairs, IDEA partnerships, etc. (der.hans, Salt, Ben, Lacey)

### 03/08
- [ ] turn retrospective tasks into GH issues (Lacey)
- [ ] outreach to meet up to exchange info / go over processes and make plans (Ben & Lacey)
- [ ] meet to fold over some volunteer role information stuff (Lacey & J)
- [ ] updated graphic assets for 2022 (Mateus)
- [ ] create issue templates that document how they should be used (Lacey & Mateus)

### 03/22 - New TODOs
- [ ] Connect J and Lucy to talk about volunteering (Salt)
- [ ] draft initial outreach message (der.hans, Ben, Lacey, Salt, anyone else)
  - https://pad.seattlematrix.org/p/SeaGL_2022_Outreach-first_message
- [ ] send message to potential groups for help with IDEA (Salt?)
  - https://pad.seattlematrix.org/p/SeaGL_2022_IDEA-first_message
- [ ] #246 brainstorm year 10 theme (Everyone)
- [ ] connect with Hans to schedule first Finance Committee meeting (Norm)
- [ ] consider changing title of committee "chair"
  - Is this scaring some folks away?
  - Alternatives: leads, champions, cat-herders, organizer, flockers, ???

### Current Committee Chairs - HELP WANTED (Salt)
- Programming & Flow - Nathan & ??
- Finance - der.hans & Norm
- Attendee Experience - ?? & ??
- Promotion & Outreach - Ben & Lacey
- Partnerships - ?? & ??
- SRE/Technical - Don & AJ
- Volunteers - J & ??
- IDEA: Inclusion, Diversity, Equity, Access - ?? & ??
- CoC: Code of Conduct - ?? & ??
- Impresario - Salt & ??
  - Still looking for apprentice impresario, anyone who is interested please volunteer or invite a friend!

### Committee Meetings (Salt)
- What are the meeting schedule for each committee? Is help needed regarding tools, frequency, etc?
- Programming & Flow - ??
- Finance - ??
- Attendee Experience - ??
- Promotion & Outreach - ??
- Partnerships - ??
- SRE/Technical - every other Wednesday at 6pm PST, off-week from all-hands
- Volunteers - ??
- IDEA: Inclusion, Diversity, Equity, Access - ??
- CoC: Code of Conduct - ??
- Impresario - ??

### Upcoming blog/social posts

- [ ] Kick-off / Volunteers Welcome (Ben, Lacey, J)
- [ ] Thursday, March 24: Keynote Nominations Open (Nathan) [?]

### Timeline
- End ~~Start~~ of March: Launch Keynote request for nominations
- At least open for two weeks: Close Keynote nominations
- Late March: OSEM ready for programming committee testing
- Tentatively April 1: Decide on virtual only or hybrid event: 
- 2 weeks after virtual/hybrid decision: post sponsor prospectus
- 1 week after testing or more: OSEM launched
- : Reach out to Keynote speakers
- TBD: CFP opens
- : Sponsorship prospectus opens
- TBD: CFP closes
- TBD: CFP Review 1
- TBD: Select Speakers
- TBD: Notify Speakers
- TBD: Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- : Finalize Program
- Tentatively October 1: Full tech run-through of technologies at Tech Meeting
- : Documentation run-through of technologies at Tech Meeting
- 1 week after run-through: Tech training for volunteers
- November 1: Pre-recorded talk videos in the hands of SeaGL
- November 4-5 (Friday/Saturday): SeaGL 2022

### Next All-Hands Meeting
- SeaGL 2022 Bi-weekly All-hands: Tuesday, April 19 @ 6pm Pacific Time
  - https://calendar.google.com/event?action=TEMPLATE&tmeid=NWhkYnVjNjQ5cDhoM3FuMmsybmpuMTZqbGVfMjAyMjA0MjBUMDEwMDAwWiBzYWx0QHNlYWdsLm9yZw&tmsrc=salt%40seagl.org

#### Committee Meetings
- Programming & Flow: 
- Finance and Partnerships: 
- Attendee Experience: 
- Promotion & Outreach: 
- SRE/Technical: Bi-Weekly, off-week from all-hands, Wed 6pm
- Volunteers: 
- IDEA: 
- CoC: 

### Check that we have note taker(s) for next meeting

# Meeting adjourned!
