### ISSUE TITLE
2022-05-03 All-Hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#255]
# 2022-05-03 SeaGL 2022 All-Hands
- May 3, 2022. 1800 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/255)
- [Shared Pad](https://pad.seattlematrix.org/p/SeaGL_2022_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2022_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/tree/main/meetings/2022)
- [Mailing list](https://groups.google.com/a/seagl.org/g/seagl2022)
- [2021 Retrospective](https://github.com/SeaGL/organization/blob/main/meetings/2021/20211115-retrospective.md)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): nomad
- Note Taker(s) for next time: 

### Metrics
- Staff: 12 (?)
- Ambassadors: 
- Social Shares: (is there a decent way to track this?)
- Blog Posts: 1 -> 2
- Sponsors: 0
- Keynote Nominations: 2 ->

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 02/08
- [ ] invite a friend to participate (*everyone*)
  - Going to keep this on until Salt feels like it and/or we have chairs for each committee
- [ ] #222 review retrospective by next meeting (everyone)
  - Each committee should complete this task at their first meeting.
- [ ] #245 review web site for needed updates by next meeting (everyone)
  - Each committee should complete this task at their first meeting.
- [ ] reach out to media sponsors and Ambassadors list about planning, filling chairs, IDEA partnerships, etc. (der.hans, Salt, Ben, Lacey)

### 03/08
- [ ] turn retrospective tasks into GH issues
- [ ] outreach to meet up to exchange info / go over processes and make plans (Ben & Lacey)
- [ ] meet to fold over some volunteer role information stuff (Lacey & J)
- [ ] updated graphic assets for 2022 (Mateus)
- [ ] create issue templates that document how they should be used (Lacey, Mateus, anyone else)

### 03/22
- [ ] Connect J and Lucy to talk about volunteering (Salt)
- [ ] draft initial outreach message (der.hans, Ben, Lacey, Salt, anyone else)
  - https://pad.seattlematrix.org/p/SeaGL_2022_Outreach-first_message
- [ ] send message to potential groups for help with IDEA (Salt?)
  - https://pad.seattlematrix.org/p/SeaGL_2022_IDEA-first_message
- [ ] #246 brainstorm year 10 theme (Everyone)
  - some brainstorming has been happening, more would be good.
- [ ] #254 consider changing title of committee "chair"

### 04/05
- [-] generate poll to ask community about virtual vs hybrid
  - poll wasn't generated and we can't keep pushing off the decision
- [-] create GH issue to set decision for virtual vs hybrid on first meeting after May 1
  - issue wasn't opened, will discuss below and make a decision

### 04/19
- [ ] promote keynote nomination submissions (everyone)

### Keynote Nominations
- https://seagl.org/news/2022/04/15/keynote-nomination.html

### Current Committee Chairs - HELP WANTED (Salt)
- Programming & Flow - Nathan & ??
- Finance - der.hans & Norm
- Attendee Experience - ?? & ??
- Promotion & Outreach - Ben & Lacey
- Partnerships - ?? & ??
- SRE/Technical - Don & AJ
- Volunteers - J & ??
- IDEA: Inclusion, Diversity, Equity, Access - ?? & ??
- CoC: Code of Conduct - ?? & ??
- Impresario - Salt & ??
  - Still looking for apprentice impresario, anyone who is interested please volunteer or invite a friend!
- Most pressing needs are Partnerships and Attendee Experience, would calm Salt's mind

### Committee Meetings (Salt)
- What are the meeting schedule for each committee? Is help needed regarding tools, frequency, etc?
- Programming & Flow - ??
- Finance - every other Monday at 4pm PT, off-week from all-hands
- Attendee Experience - ??
- Promotion & Outreach - ??
- Partnerships - ??
- SRE/Technical - every other Wednesday at 6pm PST, off-week from all-hands
- Volunteers - ??
- IDEA: Inclusion, Diversity, Equity, Access - ??
- CoC: Code of Conduct - ??
- Impresario - ??

### Upcoming blog/social posts

- [x] Kick-off / Volunteers Welcome (Ben, Lacey, J)
  - [seagl.github.io#326](https://github.com/SeaGL/seagl.github.io/issues/326)
  - Last chance for comments. Ben will publish Wednesday morning

### Timeline
- Start of April: Launch Keynote request for nominations
- At least open for two weeks: Close Keynote nominations
- Early May: OSEM ready for programming committee testing
- Tentatively May 1: Decide on virtual only or hybrid event
- 2 weeks after virtual/hybrid decision: post sponsor prospectus
- 1 week (or more) after testing: OSEM launched
- : Reach out to Keynote speakers
- TBD: CFP open
- : Sponsorship prospectus opens
- TBD: CFP closes
- TBD: CFP Review 1
- TBD: Select Speakers
- TBD: Notify Speakers
- TBD: Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- : Finalize Program
- Tentatively October 1: Full tech run-through of technologies at Tech Meeting
- : Documentation run-through of technologies at Tech Meeting
- 1 week after run-through: Tech training for volunteers
- November 1: Pre-recorded talk videos in the hands of SeaGL
- November 4-5 (Friday/Saturday): SeaGL 2022

### Next All-Hands Meeting
- SeaGL 2022 Bi-weekly All-hands: Tuesday, May 17 @ 6pm Pacific Time
  - https://calendar.google.com/event?action=TEMPLATE&tmeid=NWhkYnVjNjQ5cDhoM3FuMmsybmpuMTZqbGVfMjAyMjA0MjBUMDEwMDAwWiBzYWx0QHNlYWdsLm9yZw&tmsrc=salt%40seagl.org

#### Committee Meetings
- Programming & Flow: 
- Finance and Partnerships: Bi-Weekly, off-week from all-hands, Mon 4pm
- Attendee Experience: 
- Promotion & Outreach: 
- SRE/Technical: Bi-Weekly, off-week from all-hands, Wed 6pm
- Volunteers: 
- IDEA: 
- CoC: 

### Check that we have note taker(s) for next meeting

# Meeting adjourned!
