### ISSUE TITLE
Prod Matrix rooms setup checklist

### ISSUE THREAD

**Issue by strugee** [SeaGL/organization#317]
- [x] Make sure Patch is running somewhere
- [x] Make sure Mjolnir is running and pointed at the correct management room
- [x] Mjolnir: prod protected room list
- [x] Point Patch at meet.seagl.org
