### ISSUE TITLE
2021-05-31 All-hands

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#64]
# 2021-05-31 SeaGL 2021 bi-weekly all-hands
- May 31th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/organization/issues/64)
- [Shared Pad](https://etherpad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): der.hans
- Note Taker next meeting: 

### Metrics (previous --> current)
- Keynote nominations: 12 -->
- (keep brainstorming!)

### Previous meeting feedback
- many kudos:
  - keith: great meeting, hope to be more around in next couple of weeks
  - andrew: seems to be a good meeting format
  - deb: great to see everyone, like going through tickets
  - norm: new to all of this, interest, will need to not use tablet for meetings
  - der.hans: good meeting, look forward to catching up
  - rachel: still receiving benefit of rules without them being as strict, meetings running much more smoothly
  - salt: thanks, want to work on integrating the issues a bit, would like to hear from people we haven't heard from for a while
- GH issue emails are a bit noisy (keith has offered help for anyone having this... issue)
- Comb GH issues a bit more beforehand to expedite things

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

# Agenda

### 3/8
- [ ] #75 transition fiscal sponsorship away from the FSF (Salt and Deb)
- [ ] #78 Document the new project management system (Salt)
- [ ] #79 Finalize committee descriptions (Salt)
- [ ] #80 Fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Finance, 1x Promotion/Outreach, 1x Partnerships, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] #81 Set up asynchronous method to review feedback from last year (Salt)
- [ ] #82 Publish 2020 videos (Tech)
- [ ] #83 Ship 2020 speaker swag (Salt)

### 5/3
- [ ] #106 Talk to programming and partnerships about what to include in 2020 gift shipments (Salt)
- [ ] #110 Prepare 2021 Sponsor Prospectus (Finance and Partnerships)

### 5/17
- [ ] #122 Send instructions for everyone to help with YouTube video transcription. (Keith)
- [x] #85 Add 2021 timeline to pad, ask for addition in GH issue (Salt)
- [ ] #56 Review [draft of virtual announcement blog post](https://github.com/SeaGL/seagl.github.io/pull/245) and LGTM (Rachel and Ben)
- [x] #65 Add the note to template that "Meeting minute notes are public by default." (Salt)
- [x] #66 Review then migrate public issues from staff repo to org repo (Salt)
- [ ] #59 Finalize and send 2021 ads to Linux Magazine (Ben)
- [ ] #112 All committees have had their first meeting, and figured out whether a regularly scheduled one makes sense (Chairs)
- [x] Add Ben Cotton to the announce list moderators list (Salt)
- [x] Add a box for Fediverse contact on the keynote nomination form (in addition to existing Twitter) (Rachel)
- [ ] #67 Share/retweet keynote nomination link (Everyone)
- [ ] #68 Reach out to James Mason, lead of LFNW and OSEM maintainer (Andrew)
- [ ] #69 Put out a call for more tech volunteers, especially for OSEM/Rails on social media (Outreach)
- [ ] #70 Start planning and announcing the 2021 career expo (der.hans)
- [ ] #71 Write email to SeaGL announce list (Outreach)

## New Items
- [ ] #123 Clean-up email ratsnest
- [ ] #124 Close out 2020, that list in the corner we never look at...

### Timeline
- May 10 (Monday)*: Launch Keynote request for nominations
- May 24 (at the earliest): Close Keynote nominations
- June 15 (Tuesday)**: CFP opens
- August 5 (Thursday)*: CFP closes
- Week Of Aug 23 (choose w/ committee): CFP Review 1
- Week Of Aug 30 (choose w/ committee): Select Speakers
- September 6 (Monday)*: Notify Speakers
- September 19 (Monday): Finalize Speakers [this is the date the speakers need to have confirmed by, and that we'll need to have pulled waitlisted people up]
- September 26 (Monday)*: Finalize Program
- November 5-6 (Friday/Saturday)***: SeaGL 2021

* means a blog post accompanies
** there should be at least one additional blog post, asking for more specific things, halfway through the CFP being open

### Next Meeting
- Catch up meeting on Wednesday on June 2nd, at 8pm
  - Deb will facilitate for folks that can't make Monday's meeting
- Next regular bi-weekly all-hands Monday, June 14 @ 5pm PT

### Sign-off round (what's next, appreciations, suggestions)

# Meeting adjourned!

**Comment by altsalt** [comment]
Clean-up email ratsnest #123

**Comment by altsalt** [comment]
New Topic:  #124 Close out 2020, that list in the corner we never look at...

**Comment by altsalt** [comment]
https://github.com/SeaGL/organization/blob/master/meetings/2021/20210531-allhands.md
