### ISSUE TITLE
2021-04-19 Staff Meeting

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#73]
# 2021-04-19 SeaGL 2021 bi-weekly all-hands
- April 19th, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/staff/issues/2)
- [Shared Pad](https://etherpad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 

### Previous meeting feedback
- look forward to having a committee soon
- good meeting, excited about everything coming together
- look forward to having year 2 of virtual event

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

#### from 3/8
- [x] SeaGL/staff#3 communicate our save-the-date on social media (der.hans)
- [x] SeaGL/staff#4 begin process of moving away from FSF as a fiscal sponsor
- [ ] SeaGL/staff#5 compile list of what FSF has control over
- [x] SeaGL/staff#6 notify John Sullivan that SeaGL will be moving fiscal sponsors (Deb)
- [ ] SeaGL/staff#7 document the new project management system (Salt)
- [ ] SeaGL/staff#8 finalize committee descriptions (Salt)
- [ ] SeaGL/staff#9 fill out SeaGL 2021 staff lead seats (Salt)
- [ ] SeaGL/staff#10 set up asynchronous method to review feedback from last year (Salt)
- [ ] SeaGL/staff#11 make progress on 2020 videos
- [ ] SeaGL/staff#12 make progress on 2020 speaker swag (Salt)
- [x] SeaGL/staff#13 compile list of blog posts that need writing (Ben)
- [ ] SeaGL/staff#14 fill out 2021 timeline (Everyone)

#### from 4/5
- [x] SeaGL/staff#15 arrange meeting to discuss fiscal sponsor options (der.hans)
- [x] SeaGL/staff#16 organize tech kick-off meeting (Salt)
- [x] SeaGL/staff#17 send intro email connecting Andrew and Hager (der.hans)
- [x] SeaGL/staff#18 create GitHub issues for all of the TODOs (Salt)
- [ ] SeaGL/staff#19 decide on whether to hybrid by end of April (Salt)
- [x] SeaGL/staff#20 open issue to review last year's feedback, bring three positives, one opportunity to next meeting (Salt)
