### ISSUE TITLE
2021-05-03 Staff Meeting

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#95]
# 2021-05-03 SeaGL 2021 bi-weekly all-hands
- May 3rd, 2021. 1700 Pacific Time
- [Agenda](https://github.com/SeaGL/staff/issues/24)
- [Shared Pad](https://etherpad.seattlematrix.org/p/SeaGL_2021_all-hands)
- [Jitsi URL](https://meet.seattlematrix.org/SeaGL_2021_all-hands)
- [Previous meeting minutes](https://github.com/SeaGL/organization/blob/master/meetings/2021/)

### Check-in round
- Attendees: 
- Apologies: 
- Facilitator: 
- Note Taker(s): 

### Previous meeting feedback
- return to beginning meeting by go over norms
  - we start with intros and centering, followed by 1 minute of silence
  - often have chat in etherpad, change your name and color
  - this is how we wrap up
- notetaker role should be shared, don't make it invisible work that is often gendered

## Minute of silence (get into the SeaGL headspace)
- Review agenda
- Consider tensions, progress updates, blockers, questions
- Gather personal notes, tasks, emails

### 3/8
- [ ] SeaGL/organization#75 transition fiscal sponsorship away from the FSF
- [x] SeaGL/organization#76 compile list of what FSF has control over (der.hans)
- [ ] SeaGL/organization#78 document the new project management system (Salt)
- [ ] SeaGL/organization#79 finalize committee descriptions (Salt)
- [ ] SeaGL/organization#80 fill out SeaGL 2021 staff lead seats (Salt)
  - still looking for: 1x Finance, 1x Promotion/Outreach, 2x Partnerships, 2x Volunteers, 1x IDEA, 2x CoC
- [ ] SeaGL/organization#81 set up asynchronous method to review feedback from last year (Salt)
- [ ] SeaGL/organization#83 make progress on 2020 speaker swag (Salt)

### 4/5
- [x] SeaGL/organization#90 decide on whether to hybrid by end of April (Salt)

### 4/19
- [ ] SeaGL/staff#25 Start the conversation with the OSI about doing a 1-2 year fiscal sponsor relationship (Deb)
- [ ] SeaGL/staff#26 Begin paperwork to move to OSI as a fiscal sponsor (Deb and Salt)
- [x] SeaGL/staff#27 Change Twitter background picture to reflect 2021 date (Outreach)
- [ ] SeaGL/organization#82 Create the process to pull down, transcribe, and archive 2020 videos (Don and Keith)
- [ ] SeaGL/organization#85 Take an initial pass on the 2021 timeline (Rachel and Nathan)
- [x] SeaGL/staff#28 Start mailing list thread about virtual vs hybrid vs in person (Salt)
- [x] SeaGL/organization#92 Add Ben to the Twitter account, not just Tweetdeck (Salt)
- [x] SeaGL/staff#29 Contact github to see whether they will expand issue assignment beyond 1 contributor for open source projects (Salt)

### 5/3
- [ ]
